// Automatically generated by MockGen. DO NOT EDIT!
// Source: ./store/user_linux.go

package store

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of systemUserReader interface
type MocksystemUserReader struct {
	ctrl     *gomock.Controller
	recorder *_MocksystemUserReaderRecorder
}

// Recorder for MocksystemUserReader (not exported)
type _MocksystemUserReaderRecorder struct {
	mock *MocksystemUserReader
}

func NewMocksystemUserReader(ctrl *gomock.Controller) *MocksystemUserReader {
	mock := &MocksystemUserReader{ctrl: ctrl}
	mock.recorder = &_MocksystemUserReaderRecorder{mock}
	return mock
}

func (_m *MocksystemUserReader) EXPECT() *_MocksystemUserReaderRecorder {
	return _m.recorder
}

func (_m *MocksystemUserReader) readSystemUsers() []systemUser {
	ret := _m.ctrl.Call(_m, "readSystemUsers")
	ret0, _ := ret[0].([]systemUser)
	return ret0
}

func (_mr *_MocksystemUserReaderRecorder) readSystemUsers() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "readSystemUsers")
}
